# Generated by Django 3.1.2 on 2020-10-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueapp',
            name='web_url',
            field=models.URLField(default='test.com'),
        ),
        migrations.AlterField(
            model_name='trueapp',
            name='android_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trueapp',
            name='iphone_url',
            field=models.URLField(),
        ),
    ]
